# Generated by Django 3.2.21 on 2024-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npm', '0002_auto_20240327_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user123', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
